controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [base_link__link_01,link_01__link_02,link_02__link_03,base_link__link_04,link_04__link_05,link_05__link_06]